export const allowRoles = [
  'ROLE_CEO',
  'ROLE_ADMIN',
  'ROLE_PROJECT ADMIN',
  'ROLE_SITE ADMIN',
  'ROLE_MANAGER',
  'ROLE_SR ENGINEER',
  'ROLE_OPERATIONS',
  'ROLE_SR ARCHITECT',
  'ROLE_SITE SUPERVISOR',
];
