import { Geist, Geist_Mono, Imprima, Ubuntu } from "next/font/google";
import "./globals.css";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "../helpers/QueryProvider";
import { ThemeProvider } from "../components/theme-provider";
import { Toaster } from "../components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const custom = Imprima({
  variable: "--font-custom",
  weight: "400",
  subsets: ["latin"],
});
const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Thikedaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${custom.variable} ${ubuntu.variable} antialiased`}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <Toaster />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
