export const userInputs = [
  {
    id: 1,
    label: "Profile Pic",
    type: "file",
    placeholder: "Profile Pic",
    name: "profileImage",
  },
  {
    id: 2,
    label: "First Name",
    type: "text",
    placeholder: "First_Name",
    name: "firstname",
  },
  {
    id: 3,
    label: "Last Name",
    type: "text",
    placeholder: "Last_Name",
    name: "lastname",
  },
  {
    id: 4,
    label: "User Name",
    type: "text",
    placeholder: "User Name",
    disabled: true,
    name: "username",
  },
  {
    id: 5,
    label: "Email",
    type: "text",
    disabled: true,
    placeholder: "Email",
    name: "email",
  },
  {
    id: 6,
    label: "Phone/Mobile No.",
    type: "number",
    placeholder: "Phone Number",
    name: "phone",
  },
  // {
  //   id: 7,
  //   label: "Password",
  //   type: "password",
  //   placeholder: "Password",
  //   name: "password",
  // },
  {
    id: 8,
    label: "State",
    type: "select",
    placeholder: "State",
    name: "state",
  },
  {
    id: 9,
    label: "City",
    type: "select",
    placeholder: "City",
    name: "city",
  },
  {
    id: 10,
    label: "Country",
    type: "select",
    placeholder: "Country",
    name: "country",
  },
  {
    id: 11,
    label: "Zip Code",
    type: "text",
    placeholder: "Zip Code",
    name: "zipCode",
  },
];

export const addressInputs = [
  {
    id: 1,
    label: "Address",
    type: "text",
    placeholder: "Address",
    name: "address",
  },
  {
    id: 2,
    label: "State",
    type: "select",
    placeholder: "State",
    name: "state",
  },
  {
    id: 3,
    label: "City",
    type: "select",
    placeholder: "City",
    name: "city",
  },
  {
    id: 4,
    label: "Zip Code",
    type: "text",
    placeholder: "Zip Code",
    name: "zipCode",
  },
  {
    id: 5,
    label: "Near by",
    type: "text",
    placeholder: "Near by",
    name: "nearBy",
  },
  {
    id: 6,
    label: "Phone Number",
    type: "text",
    placeholder: "Phone Number",
    name: "phoneNumber",
  },
  {
    id: 6,
    label: "Country",
    type: "select",
    placeholder: "Country",
    name: "country",
  }
];

export const productInputs = [
  {
    id: 1,
    label: "State",
    type: "select",
    placeholder: "State",
    name: "serviceLocationState",
  },
  {
    id: 2,
    label: "City",
    type: "select",
    placeholder: "City",
    name: "serviceLocationCity",
  },
  {
    id: 3,
    label: "Title",
    type: "text",
    name: "title",
    placeholder: "Title for design",
  },
  {
    id: 4,
    label: "Plot Length",
    name: "plotLength",
    type: "number",
    placeholder: "500",
  },
  {
    id: 5,
    label: "Plot Width",
    name: "plotWidth",
    type: "number",
    placeholder: "400",
  },
  {
    id: 6,
    label: "Number of Bedrooms",
    name: "numberOfBedrooms",
    type: "number",
    placeholder: "2",
  },
  {
    id: 7,
    label: "Number of Toilet",
    name: "numberOfToilets",
    type: "number",
    placeholder: "2",
  },
  {
    id: 8,
    label: "Number of Floor",
    name: "numberOfFloor",
    type: "number",
    placeholder: "3",
  },
  {
    id: 9,
    label: "Building Type",
    name: "buildingType",
    type: "select",
    option: ["Residintal", "Commercial", "Industrial", "Hospital", "Mixed Use"],
    placeholder: "Select one",
  },
  {
    id: 10,
    label: "As per Vastu?",
    name: "isVastu",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 11,
    label: "Stilt Parking",
    name: "isStiltdParking",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 12,
    label: "Purpose",
    type: "select",
    name: "purpose",
    option: ["Rental", "Self Use"],
    placeholder: "select one",
  },
  {
    id: 13,
    label: "Special Feature",
    name: "specialFeature",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 14,
    label: "Design Description",
    name: "description",
    type: "text",
    placeholder: "write here...",
  },
  {
    id: 15,
    label: "2D Floor Plan",
    name: "twoDImage",
    type: "file",
    placeholder: "2D Floor Plan",
  },
  {
    id: 16,
    label: "3D View",
    name: "threeDImage",
    type: "file",
    placeholder: "3D View",
  },
  {
    id: 17,
    label: "CAD File",
    name: "cadImage",
    type: "file",
    placeholder: "CAD File",
  },
  {
    id: 18,
    label: "Price for CAD File",
    name: "cadImagePrice",
    type: "number",
    placeholder: "Price for CAD File",
  },
];

export const architectInput = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "Enter name as per ID proof",
    name: "name",
  },
  {
    id: 2,
    label: "Designation",
    type: "text",
    placeholder: "Architect Designation",
    name: "designation",
  },
  {
    id: 3,
    label: "Company Name",
    type: "text",
    placeholder: "Company Name",
    name: "companyName",
  },
  {
    id: 4,
    label: "Address",
    type: "text",
    placeholder: "Address",
    name: "address",
  },
  {
    id: 5,
    label: "GST",
    type: "file",
    placeholder: "GST",
    name: "gstImage",
  },
  {
    id: 6,
    label: "PAN",
    type: "file",
    placeholder: "PAN",
    name: "panImage",
  },
  {
    id: 7,
    label: "Payment Method Bank Account/UPI ",
    type: "text",
    placeholder: "Bank Account/UPI",
    name: "paymentMethod",
  },
  {
    id: 8,
    label: "Bank Details",
    type: "file",
    placeholder: "Bank Details",
    name: "bankDetailsImage",
  },
  {
    id: 9,
    label: "COA License Number",
    type: "file",
    placeholder: "COA License Number",
    name: "coaLicenseImage",
  },
  {
    id: 10,
    label: "Other Licence",
    type: "file",
    placeholder: "Other Licence",
    name: "otherLicenseImage",
  },
  {
    id: 11,
    label: "Qualification",
    type: "text",
    placeholder: "Qualification",
    name: "qualificationDocument",
  },
  {
    id: 12,
    label: "Services Offered",
    type: "text",
    placeholder: "Services Offered",
    name: "servicesOffered",
  },
  //   {
  //     id: 13,
  //     label: "Qualification Document",
  //     type: "file",
  //  
  //     placeholder: "Qualification Document",
  //     name: "qualification",
  //   },
  {
    id: 14,
    label: "Aadhar Number Verification",
    type: "file",
    placeholder: "Aadhar Number",
    name: "aadharImage",
  },
  {
    id: 15,
    label: "Date of Birth",
    type: "date",
    placeholder: "Date of Birth",
    name: "dateOfBirth",
  },
  {
    id: 16,
    label: "Business Contact Number",
    type: "text",
    placeholder: "Business Contact Number",
    name: "businessContactNumber",
  },
  {
    id: 17,
    label: "Service Location State",
    type: "select",
    placeholder: "State",
    name: "serviceLocationState",
  },
  {
    id: 18,
    label: "Service Location City",
    type: "select",
    placeholder: "City",
    name: "serviceLocationCity",
  },
  {
    id: 19,
    label: "Years of Experience",
    type: "text",
    placeholder: "Years of Experience",
    name: "yearsOfExperience",
  },
  {
    id: 20,
    label: "Year of Graduation",
    type: "text",
    placeholder: "Year of Graduation",
    name: "yearOfGraduation",
  },
  // {
  //   id: 21,
  //   label: "Approval Status",
  //   type: "text",
  //   placeholder: "Approval Status",
  //   name: "approvalStatus",
  // },
];

export const uploadPortfolioInputs = [
  {
    id: 1,
    label: "Suitable Location State",
    type: "select",
    placeholder: "State",
    name: "serviceLocationState",
  },
  {
    id: 2,
    label: "Suitable Location City",
    type: "select",
    placeholder: "City",
    name: "serviceLocationCity",
  },
  {
    id: 3,
    label: "Title",
    type: "text",
    name: "title",
    placeholder: "Title for design",
  },
  {
    id: 4,
    label: "Plot Length",
    name: "plotLength",
    type: "number",
    placeholder: "Plot Length in ft",
  },
  {
    id: 5,
    label: "Plot Width",
    name: "plotWidth",
    type: "number",
    placeholder: "Plot Width in ft",
  },
  {
    id: 6,
    label: "Number of Bedrooms",
    name: "numberOfBedrooms",
    type: "number",
    placeholder: "2",
  },
  {
    id: 7,
    label: "Number of Toilet",
    name: "numberOfToilets",
    type: "number",
    placeholder: "2",
  },
  {
    id: 8,
    label: "Number of Floor",
    name: "numberOfFloor",
    type: "number",
    placeholder: "3",
  },
  {
    id: 9,
    label: "Building Type",
    name: "buildingType",
    type: "select",
    option: ["Residential", "Commercial", "Industrial", "Hospital", "Mixed Use"],
    placeholder: "Select one",
  },
  {
    id: 10,
    label: "As per Vastu?",
    name: "isVastu",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 11,
    label: "Stilt Parking",
    name: "isStiltdParking",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 12,
    label: "Purpose",
    type: "select",
    name: "purpose",
    option: ["Rental", "Self Use"],
    placeholder: "select one",
  },
  {
    id: 13,
    label: "Special Feature",
    name: "specialFeature",
    type: "select",
    option: ["Yes", "No"],
    placeholder: "Select One",
  },
  {
    id: 14,
    label: "Design Description",
    name: "description",
    type: "text",
    placeholder: "write here...",
  },
  {
    id: 15,
    label: "2D Floor Plan",
    name: "twoDImage",
    type: "file",
    placeholder: "2D Floor Plan",
  },
  {
    id: 16,
    label: "3D View",
    name: "threeDImage",
    type: "file",
    placeholder: "3D View",
  },
  {
    id: 17,
    label: "CAD File",
    name: "cadImage",
    type: "file",
    placeholder: "CAD File",
  },
  {
    id: 18,
    label: "Price for CAD File",
    name: "cadImagePrice",
    type: "number",
    placeholder: "Price for CAD File",
  },
];

export const categoryInputs = [
  {
    id: 1,
    label: "Category",
    type: "text",
    placeholder: "Enter Category...",
    name: "name",
  },
  {
    id: 2,
    label: "Unit",
    type: "text",
    placeholder: "Unit",
    name: "unit",
  },
  {
    id: 3,
    label: "Position",
    type: "number",
    placeholder: "Enter Position...",
    name: "position",
  },
  {
    id: 4,
    label: "Photo",
    type: "file",
    placeholder: "Upload Category Image",
    name:"categoryImage",
  },
  {
    id: 5,
    label: "Active",
    type: "checkbox",
    // placeholder: "Enter true/false...",
    name: "active",
  },
];

export const dealersInputs = [
  {
    id: 1,
    label: "name",
    type: "text",
    placeholder: "Enter Name as per ID Proof",
    name: "name",
  },
  {
    id: 2,
    label: "Designation",
    type: "text",
    placeholder: "Enter Designation",
    name: "designation",
  },
  {
    id: 3,
    label: "Company Name",
    type: "text",
    placeholder: "Enter Company/Shop Name ",
    name: "companyNameShopName",
  },
  {
    id: 4,
    label: "Address",
    type: "text",
    placeholder: "Enter Your Address",
    name: "address",
  },
  {
    id: 5,
    label: "GST",
    type: "file",
    placeholder: "GST",
    name: "gstImage",
  },
  {
    id: 6,
    label: "PAN",
    type: "file",
    placeholder: "PAN",
    name: "panImage",
  },
  {
    id: 7,
    label: "Bank Details",
    type: "file",
    placeholder: "Bank Details",
    name: "bankDetailsImage",
  },
  {
    id: 8,
    label: "UPI Details",
    type: "text",
    placeholder: "",
    name: "upiDetails",
  },
  {
    id: 9,
    label: "Aadhar Number",
    type: "file",
    placeholder: "Aadhar Card",
    name: "aadharImage",
  },
  {
    id: 10,
    label: "Date Of Company Formation",
    type: "date",
    placeholder: "Date of Company Formation",
    name: "dateOfCompanyFormation",
  },
  {
    id: 11,
    label: "Business Contact Number",
    type: "text",
    placeholder: "Enter Business Contact Number...",
    name: "businessContactNumber",
  },
  {
    id: 12,
    label: "Service Location State",
    type: "select",
    placeholder: "State",
    name: "serviceLocationState",
  },
  {
    id: 13,
    label: "Service Location City",
    type: "select",
    placeholder: "City",
    name: "serviceLocationCity",
  },
  {
    id: 14,
    label: "Radius Of Delivery",
    type: "text",
    placeholder: "Enter Radius Of Delivery...",
    name: "radiusOfDelivery",
  },
  {
    id: 15,
    label: "Merchant Type",
    type: "text",
    placeholder: "Enter type...",
    name: "merchantType",
  },
];

export const dealeruploadPortfolioInputs = [
  {
    id: 1,
    label: "Suitable Location State",
    type: "select",
    placeholder: "State",
    name: "serviceLocationState",
  },
  {
    id: 2,
    label: "Suitable Location City",
    type: "select",
    placeholder: "City",
    name: "serviceLocationCity",
  },
  {
    id: 3,
    label: "Product Category",
    type: "select",
    placeholder: "Category",
    name: "category",
  },
  {
    id: 4,
    label: "Existing Product Name",
    type: "select",
    placeholder: "Product",
    name: "existname",
  },
  {
    id: 5,
    label: "Product Name",
    type: "text",
    placeholder: "Product",
    name: "name",
  },
  {
    id: 6,
    label: "Photo",
    type: "file",
    placeholder: "Upload Product Image",
    name: "productImage",
  },
  {
    id: 7,
    label: "Unit",
    type: "select",
    placeholder: "Product Unit",
    name: "unit",
  },
  {
    id: 8,
    label: "Minimum Quantity",
    type: "number",
    placeholder: "Minimum  Quantity",
    name: "minQuantity",
  },
  {
    id: 9,
    label: "Maximum Quantity",
    type: "number",
    placeholder: "Maximum  Quantity",
    name: "maxQuantity",
  },
  {
    id: 10,
    label: "Price",
    type: "number",
    placeholder: "Product Price",
    name: "price",
  },
  {
    id: 11,
    label: "Description One",
    type: "text",
    placeholder: "Enter the Product Description One",
    name: "descriptionOne",
  },
  {
    id: 12,
    label: "Description Two",
    type: "text",
    placeholder: "Enter the Product Description Two",
    name: "descriptionTwo",
  },
  {
    id: 13,
    label: "Description Three",
    type: "text",
    placeholder: "Enter the Product Description Three",
    name: "descriptionThree",
  },
]

export const getDashboardProfileForm = (role) => {
  switch (role) {
    case "ROLE_USER":
      return userInputs;

    case "ROLE_ARCHITECT":
      return architectInput;

    case "ROLE_CONTRACTOR":
      return dealersInputs;

    case "manager":
      return architectInput;

    case "ROLE_DEALER":
      return architectInput;

    default:
      break;
  }
};
